test

diff --git a/.github/workflows/ai-api-calls.yml b/.github/workflows/ai-api-calls.yml
--- a/.github/workflows/ai-api-calls.yml
+++ b/.github/workflows/ai-api-calls.yml
@@ -142,53 +142,58 @@ jobs:
       # Call Studio.d-id API to generate a talk speaking the above script
       # I paid the Lite plan on https://studio.d-id.com which can generate audio and animation, but not allowed to generate video clips, which is on Premium plan
 
-      - name: Update D-ID voice input json
-        run: |
-          # cat ${PROMPT_D_ID_VOICE_JSON} | jq '.input.text'
-          export SPEAKING_SCRIPT=$(cat $SPEAKING_SCRIPT_FILE)
-          jq --arg newkey "${SPEAKING_SCRIPT}" '.script.input = $newkey' ${PROMPT_D_ID_VOICE_JSON} > tmp-file.json
-          mv tmp-file.json ${PROMPT_D_ID_VOICE_JSON}
+      # # Tested, uncomment when got new subscription
+      # - name: Update D-ID voice input json
+      #   run: |
+      #     # cat ${PROMPT_D_ID_VOICE_JSON} | jq '.input.text'
+      #     export SPEAKING_SCRIPT=$(cat $SPEAKING_SCRIPT_FILE)
+      #     jq --arg newkey "${SPEAKING_SCRIPT}" '.script.input = $newkey' ${PROMPT_D_ID_VOICE_JSON} > tmp-file.json
+      #     mv tmp-file.json ${PROMPT_D_ID_VOICE_JSON}
 
-          echo 'Done json update'
-          cat ${PROMPT_D_ID_VOICE_JSON} | jq .
+      #     echo 'Done json update'
+      #     cat ${PROMPT_D_ID_VOICE_JSON} | jq .
 
-      - name: Generate D_ID voice talk 
-        run: |
-          curl --request POST \
-            --url https://api.d-id.com/talks \
-            --header 'accept: application/json' \
-            --header "authorization: Bearer ${{ secrets.D_ID_API_KEY }}" \
-            --header 'content-type: application/json' \
-            --data @${PROMPT_D_ID_VOICE_JSON} > tmp-d-id-resp.json
+      # # Tested, uncomment when got new subscription
+      # - name: Generate D_ID voice talk 
+      #   run: |
+      #     curl --request POST \
+      #       --url https://api.d-id.com/talks \
+      #       --header 'accept: application/json' \
+      #       --header "authorization: Bearer ${{ secrets.D_ID_API_KEY }}" \
+      #       --header 'content-type: application/json' \
+      #       --data @${PROMPT_D_ID_VOICE_JSON} > tmp-d-id-resp.json
 
-          D_ID_TALK_STATUS=$(cat tmp-d-id-resp.json | jq '.status')
-          if [[ "$D_ID_TALK_STATUS" != "created" ]]; then
-            echo "API status error from D_ID Talk Task: $D_ID_TALK_STATUS"
-            cat tmp-d-id-resp.json
-            exit 1
-          else
-            D_ID_TALK_ID=$(cat tmp-d-id-resp.json | jq '.id')
-            echo "Talk created, task id: $D_ID_TALK_ID"
-          fi
+      #     D_ID_TALK_STATUS=$(cat tmp-d-id-resp.json | jq '.status')
+      #     if [[ "$D_ID_TALK_STATUS" != "created" ]]; then
+      #       echo "API status error from D_ID Talk Task: $D_ID_TALK_STATUS"
+      #       cat tmp-d-id-resp.json
+      #       exit 1
+      #     else
+      #       D_ID_TALK_ID=$(cat tmp-d-id-resp.json | jq '.id')
+      #       echo "Talk created, task id: $D_ID_TALK_ID"
+      #     fi
 
-      - name: List D_ID voice talk 
-        run: |
-          curl --request GET \
-          --url https://api.d-id.com/talks \
-          --header 'accept: application/json' \
-          --header "authorization: Bearer ${{ secrets.D_ID_API_KEY }}" > tmp-d-id-resp.json
-          cat tmp-d-id-resp.json | jq '.talks[].audio_url'
+      # # Tested, uncomment when got new subscription
+      # - name: List D_ID voice talk 
+      #   run: |
+      #     curl --request GET \
+      #     --url https://api.d-id.com/talks \
+      #     --header 'accept: application/json' \
+      #     --header "authorization: Bearer ${{ secrets.D_ID_API_KEY }}" > tmp-d-id-resp.json
+      #     cat tmp-d-id-resp.json | jq '.talks[].audio_url'
 
-      - name: Update D-ID video input json
-        run: |
-          # cat ${PROMPT_D_ID_CLIP_JSON} | jq '.input.text'
-          export SPEAKING_SCRIPT=$(cat $SPEAKING_SCRIPT_FILE)
-          jq --arg newkey "${SPEAKING_SCRIPT}" '.script.input = $newkey' ${PROMPT_D_ID_CLIP_JSON} > tmp-file.json
-          mv tmp-file.json ${PROMPT_D_ID_CLIP_JSON}
+      # # Tested, uncomment when got new subscription
+      # - name: Update D-ID video input json
+      #   run: |
+      #     # cat ${PROMPT_D_ID_CLIP_JSON} | jq '.input.text'
+      #     export SPEAKING_SCRIPT=$(cat $SPEAKING_SCRIPT_FILE)
+      #     jq --arg newkey "${SPEAKING_SCRIPT}" '.script.input = $newkey' ${PROMPT_D_ID_CLIP_JSON} > tmp-file.json
+      #     mv tmp-file.json ${PROMPT_D_ID_CLIP_JSON}
 
-          echo 'Done json update'
-          cat ${PROMPT_D_ID_CLIP_JSON} | jq .
+      #     echo 'Done json update'
+      #     cat ${PROMPT_D_ID_CLIP_JSON} | jq .
 
+      # # Tested via API document console, uncomment when got new subscription
       # # Call Video AI API to let the above person speak out that script from a prompt
       # I paid the Lite plan on https://studio.d-id.com which can generate audio and animation, but not allowed to generate video clips, which is on Premium plan
       # - name: Generate video 
